// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wcs.Data;

#nullable disable

namespace Wcs.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(WcsDbContext))]
    [Migration("20260730075824_FixPieceIdempotencyIndexExcludeArchived")]
    partial class FixPieceIdempotencyIndexExcludeArchived
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Wcs.Data.Agv", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgvNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgvNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_agv_agv_no");

                    b.ToTable("agv", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.Alarm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PieceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AckedAt")
                        .HasDatabaseName("IX_alarm_acked_at");

                    b.HasIndex("PieceId");

                    b.ToTable("alarm", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.B2B.ApiCallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("called_at");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_ip");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("http_method");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("http_status_code");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_body");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseStatus")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("response_status");

                    b.HasKey("Id");

                    b.HasIndex("CalledAt")
                        .HasDatabaseName("IX_api_call_log_called_at");

                    b.HasIndex("Endpoint")
                        .HasDatabaseName("IX_api_call_log_endpoint");

                    b.ToTable("api_call_log", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.B2B.Box", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch");

                    b.Property<string>("BizDay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("biz_day");

                    b.Property<string>("BoxNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("box_no");

                    b.Property<string>("ChuteNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("chute_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EndTime")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.HasKey("Id");

                    b.HasIndex("BizDay", "Batch")
                        .HasDatabaseName("IX_box_biz_day_batch");

                    b.HasIndex("BizDay", "Batch", "BoxNo")
                        .IsUnique()
                        .HasDatabaseName("IX_box_biz_day_batch_box_no");

                    b.ToTable("box", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.B2B.BoxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<long>("BoxId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("box_id");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qty");

                    b.HasKey("Id");

                    b.HasIndex("BoxId")
                        .HasDatabaseName("IX_box_item_box_id");

                    b.ToTable("box_item", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.B2B.TestData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("Barcode2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode2");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch");

                    b.Property<string>("BizDay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("biz_day");

                    b.Property<string>("ChuteNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("chute_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ReceiveTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("receive_time");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_test_data_barcode");

                    b.HasIndex("BizDay")
                        .HasDatabaseName("IX_test_data_biz_day");

                    b.HasIndex("BizDay", "Batch")
                        .HasDatabaseName("IX_test_data_biz_day_batch");

                    b.ToTable("test_data", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.B2B.TestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch");

                    b.Property<string>("BizDay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("biz_day");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EquipmentNo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("equipment_no");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("log_time");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("log_type");

                    b.Property<string>("Pid")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("pid");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long?>("TestDataId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_data_id");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_test_log_barcode");

                    b.HasIndex("LogTime")
                        .HasDatabaseName("IX_test_log_log_time");

                    b.HasIndex("LogType")
                        .HasDatabaseName("IX_test_log_log_type");

                    b.HasIndex("TestDataId")
                        .HasDatabaseName("IX_test_log_test_data_id");

                    b.HasIndex("BizDay", "LogType", "LogTime")
                        .HasDatabaseName("IX_test_log_biz_day_log_type_log_time");

                    b.ToTable("test_log", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.B2B.WorkResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch");

                    b.Property<string>("BizDay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("biz_day");

                    b.Property<string>("ChuteNo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("chute_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("BizDay", "Batch")
                        .HasDatabaseName("IX_work_result_biz_day_batch");

                    b.ToTable("work_result", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.Cell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId", "CellNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_cell_destination_cell_no");

                    b.ToTable("cell", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.CellAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CellId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CellId")
                        .IsUnique()
                        .HasDatabaseName("UQ_cell_assignment_cell_active")
                        .HasFilter("\"ReleasedAt\" IS NULL");

                    b.HasIndex("OrderId");

                    b.ToTable("cell_assignment", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.ChuteDetail", b =>
                {
                    b.Property<long>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultFullQty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastClearedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PrinterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkFullQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DestinationId");

                    b.HasIndex("PrinterId");

                    b.ToTable("chute_detail", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.Destination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChuteNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XminRowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChuteNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_destination_chute_no");

                    b.ToTable("destination", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.DestinationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<long>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId", "At")
                        .HasDatabaseName("IX_destination_event_dest_at");

                    b.ToTable("destination_event", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.Induction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InductionNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InductionNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_induction_induction_no");

                    b.ToTable("induction", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.OperationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SorterChuteNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("At")
                        .HasDatabaseName("IX_operation_log_at");

                    b.HasIndex("SorterChuteNo", "At")
                        .HasDatabaseName("IX_operation_log_sorter_at");

                    b.ToTable("operation_log", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortedQty")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XminRowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_order_item_barcode");

                    b.HasIndex("OrderId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("UQ_order_item_order_barcode");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.Piece", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AgvId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientTs")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepositedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InductionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XminRowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgvId");

                    b.HasIndex("InductionId");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("IX_piece_order_item");

                    b.HasIndex("PId")
                        .IsUnique()
                        .HasDatabaseName("UQ_piece_pid_active_status")
                        .HasFilter("\"IsActive\" = 1 AND \"Status\" IN ('DEPOSITED','CELL_ASSIGNED','LOADED') AND \"ArchivedAt\" IS NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_piece_status");

                    b.HasIndex("DestinationId", "DepositedAt")
                        .HasDatabaseName("IX_piece_dest_deposited");

                    b.HasIndex("DestinationId", "Status")
                        .HasDatabaseName("IX_piece_dest_status");

                    b.HasIndex("PId", "IsActive")
                        .HasDatabaseName("IX_piece_pid_active");

                    b.ToTable("piece", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.PieceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientTs")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("PieceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At")
                        .HasDatabaseName("IX_piece_event_at");

                    b.HasIndex("PieceId", "At")
                        .HasDatabaseName("IX_piece_event_piece_at");

                    b.ToTable("piece_event", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.PlcEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewVal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OldVal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Register")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At")
                        .HasDatabaseName("IX_plc_event_at");

                    b.ToTable("plc_event", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.Printer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnInfo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrinterNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrinterNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_printer_printer_no");

                    b.ToTable("printer", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.SorterCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CSeq")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CWrittenAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CellId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepositedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("PieceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RCellNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RSeq")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TiltedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("PieceId");

                    b.ToTable("sorter_command", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.WcsOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestAssignType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DestAssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefNo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XminRowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("WorkBatchId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_wcs_order_batch_order_no");

                    b.HasIndex("WorkBatchId", "Status")
                        .HasDatabaseName("IX_wcs_order_batch_status");

                    b.ToTable("wcs_order", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.WorkBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaveNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("XminRowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkDate", "BatchNo", "WaveNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_work_batch_date_batch_wave");

                    b.ToTable("work_batch", (string)null);
                });

            modelBuilder.Entity("Wcs.Data.Alarm", b =>
                {
                    b.HasOne("Wcs.Data.Piece", "Piece")
                        .WithMany("Alarms")
                        .HasForeignKey("PieceId");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Wcs.Data.B2B.BoxItem", b =>
                {
                    b.HasOne("Wcs.Data.B2B.Box", "Box")
                        .WithMany("Items")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Wcs.Data.Cell", b =>
                {
                    b.HasOne("Wcs.Data.Destination", "Destination")
                        .WithMany("Cells")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Wcs.Data.CellAssignment", b =>
                {
                    b.HasOne("Wcs.Data.Cell", "Cell")
                        .WithMany("Assignments")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wcs.Data.WcsOrder", "Order")
                        .WithMany("CellAssignments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cell");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wcs.Data.ChuteDetail", b =>
                {
                    b.HasOne("Wcs.Data.Destination", "Destination")
                        .WithOne("ChuteDetail")
                        .HasForeignKey("Wcs.Data.ChuteDetail", "DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wcs.Data.Printer", "Printer")
                        .WithMany("ChuteDetails")
                        .HasForeignKey("PrinterId");

                    b.Navigation("Destination");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("Wcs.Data.DestinationEvent", b =>
                {
                    b.HasOne("Wcs.Data.Destination", "Destination")
                        .WithMany("Events")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Wcs.Data.OrderItem", b =>
                {
                    b.HasOne("Wcs.Data.WcsOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wcs.Data.Piece", b =>
                {
                    b.HasOne("Wcs.Data.Agv", "Agv")
                        .WithMany()
                        .HasForeignKey("AgvId");

                    b.HasOne("Wcs.Data.Destination", "Destination")
                        .WithMany("Pieces")
                        .HasForeignKey("DestinationId");

                    b.HasOne("Wcs.Data.Induction", "Induction")
                        .WithMany()
                        .HasForeignKey("InductionId");

                    b.HasOne("Wcs.Data.OrderItem", "OrderItem")
                        .WithMany("Pieces")
                        .HasForeignKey("OrderItemId");

                    b.Navigation("Agv");

                    b.Navigation("Destination");

                    b.Navigation("Induction");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Wcs.Data.PieceEvent", b =>
                {
                    b.HasOne("Wcs.Data.Piece", "Piece")
                        .WithMany("Events")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Wcs.Data.SorterCommand", b =>
                {
                    b.HasOne("Wcs.Data.Cell", "Cell")
                        .WithMany("Commands")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wcs.Data.Piece", "Piece")
                        .WithMany("Commands")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cell");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Wcs.Data.WcsOrder", b =>
                {
                    b.HasOne("Wcs.Data.Destination", "Destination")
                        .WithMany("Orders")
                        .HasForeignKey("DestinationId");

                    b.HasOne("Wcs.Data.WorkBatch", "WorkBatch")
                        .WithMany("Orders")
                        .HasForeignKey("WorkBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("WorkBatch");
                });

            modelBuilder.Entity("Wcs.Data.B2B.Box", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wcs.Data.Cell", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Commands");
                });

            modelBuilder.Entity("Wcs.Data.Destination", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("ChuteDetail");

                    b.Navigation("Events");

                    b.Navigation("Orders");

                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("Wcs.Data.OrderItem", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("Wcs.Data.Piece", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Commands");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Wcs.Data.Printer", b =>
                {
                    b.Navigation("ChuteDetails");
                });

            modelBuilder.Entity("Wcs.Data.WcsOrder", b =>
                {
                    b.Navigation("CellAssignments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wcs.Data.WorkBatch", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
